website/chars/urls.py
from django.urls import path

from . import views

app_name = "chars"
urlpatterns = [
    path("", views.index, name="index")
]

website/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>", views.detail, name="detail"),
    path("<int:question_id>/results/", views.results, name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include("polls.urls")),
    path('chars/', include("chars.urls")),
    path('admin/', admin.site.urls),
]

website/chars/models.py
from django.db import models

class Character(models.Model):
  char_name = models.CharField("Character Name", max_length=20)
  weight = models.IntegerField("Weight")
  num_jumps = models.IntegerField("Number of Jumps")
  max_run_vel = models.DecimalField("Maximum Run Velocity", max_digits=5, decimal_places=3)
  jump_height = models.DecimalField("Jump Height", max_digits=5, decimal_places=2)
  hop_height = models.DecimalField("Shorthop Height", max_digits=5, decimal_places=2)
  air_jump_height = models.DecimalField("Air Jump Height", max_digits=5, decimal_places=2)
  max_h_air_speed = models.DecimalField("Maximum Horizontal Air Speed", max_digits=5, decimal_places=3)
  fastfall_speed = models.DecimalField("Fastfall Speed", max_digits=5, decimal_places=3)
  has_walljump = models.BooleanField("Has Walljump")
  franchise = models.CharField(max_length=50)
  backstory = models.CharField(max_length=250)
  codename = models.CharField("Codename", max_length=20)
  img_url = models.CharField("Image File URL", max_length=50)

  def __str__(self):
    return self.char_name

website/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
  question_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField("date published")
  def __str__(self):
    return self.question_text
  
  def was_published_recently(self):
    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  votes = models.IntegerField(default=0)
  def __str__(self):
    return self.choice_text

website/chars/views.py
from django.shortcuts import render
from django.template import loader
from .models import Character

def index(request):
  chars = Character.objects.all()
  char_fields = Character._meta.get_fields()
  return render(request, "chars/index.html", {"chars": chars, "char_fields": char_fields})

website/polls/views.py
from django.http import HttpResponse, Http404
from django.template import loader
from django.shortcuts import render, get_object_or_404

from .models import Question

## with shortcut
def index(request):
  latest_question_list = Question.objects.order_by("pub_date")[:5]
  context = {
    "latest_question_list": latest_question_list
  }
  return render(request, "polls/index.html", context)

## without shortcut
# def index(request):
#   latest_question_list = Question.objects.order_by("pub_date")[:5]
#   template = loader.get_template("polls/index.html")
#   context = {
#     "latest_question_list": latest_question_list
#   }
#   return HttpResponse(template.render(context, request))

###v3 shortcut
def detail(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  return render(request, "polls/detail.html", {"question": question})
# ###v2
# def detail(request, question_id):
#   try:
#     question = Question.objects.get(pk=question_id)
#   except Question.DoesNotExist:
#     raise Http404("Question does not exist")
#   return render(request, "polls/detail.html", {"question": question})
###v1
# def detail(request, question_id):
#   return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
  return HttpResponse("You're looking at the results of question %s." % question_id)

def vote(request, question_id):
  return HttpResponse("You're voting on question %s." % question_id)

website/chars/templates/chars/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Character Select</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'chars/index.css' %}"
    />
  </head>
  <body>
    Hello, world. This is the characters screen.
    <nav></nav>
    <section id="char-select">
      <h1>Char Select</h1>
      <div id="char-select-container">
        {% for char in chars %}
        <div class="char-tile">
          <div class="char-img-wrapper">
            <img src="{% static 'chars/images/' %}{{char.img_url}}" />
          </div>
          <div class="char-name">{{ char.char_name }}</div>
        </div>
        {% endfor %}
      </div>
    </section>
    <section id="char-filters">
      <h1>Filters</h1>
      <div id="char-filter-container">
        <div class="char-filter-slider">
          <label for="weight">Weight</label>
          <input id="weight" type="range" min="{{}}" />
        </div>
      </div>
    </section>
  </body>
</html>

website/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Polls</title>
  </head>
  <body>
    <h1>{{ question.question_text }}</h1>
    <ul>
      {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}</li>
      {% endfor %}
    </ul>
  </body>
</html>

website/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Polls</title>
  </head>
  <body>
    {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
      <li>
        <a href="{% url 'polls:detail' question.id %}">
          {{ question.question_text }}
        </a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
  </body>
</html>